import React from 'react';
import { ArrowLeft } from 'lucide-react';
import { LegalFooter } from './LegalFooter';

interface TermsViewProps {
  onNavigate: (view: any) => void;
}

export const TermsView: React.FC<TermsViewProps> = ({ onNavigate }) => {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col font-sans">
      
      {/* Top Bar */}
      <div className="border-b border-border py-3 px-4 sm:px-8 bg-background/80 backdrop-blur-sm sticky top-0 z-30">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <button
            onClick={() => onNavigate('app')}
            className="flex items-center gap-2 text-xs font-mono text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Back to Time Matrix</span>
          </button>
          <span className="sec-label">Terms & Conditions</span>
        </div>
      </div>

      {/* Main Content */}
      <main className="flex-1 max-w-2xl mx-auto px-4 sm:px-6 py-12 sm:py-16 space-y-6">
        
        <header className="space-y-1">
          <div className="sec-label">Legal</div>
          <h1 className="text-2xl sm:text-3xl font-semibold tracking-tightest text-foreground">
            Terms & Conditions
          </h1>
          <p className="text-xs font-mono text-muted-foreground">Effective: 2026 • Arigato Labs</p>
        </header>

        <div className="space-y-6 text-xs sm:text-sm text-muted-foreground leading-relaxed">
          
          <section className="space-y-1.5">
            <h2 className="text-sm font-semibold text-foreground">1. Agreement</h2>
            <p>
              By accessing or using Time Matrix, you agree to be bound by these Terms & Conditions and our Privacy Policy.
            </p>
          </section>

          <section className="space-y-1.5">
            <h2 className="text-sm font-semibold text-foreground">2. The Service</h2>
            <p>
              Time Matrix is provided by <strong>Arigato Labs</strong> for personal logging, analytics, and time-optimization of short-form video content.
            </p>
          </section>

          <section className="space-y-1.5">
            <h2 className="text-sm font-semibold text-foreground">3. User Responsibility</h2>
            <p>
              You are responsible for maintaining the accuracy of view count numbers recorded during 24-hour check-ins and the content of notes or images uploaded.
            </p>
          </section>

          <section className="space-y-1.5">
            <h2 className="text-sm font-semibold text-foreground">4. Acceptable Use</h2>
            <p>
              You agree not to disrupt, reverse-engineer, attack, or abuse the application, database, or media storage endpoints.
            </p>
          </section>

          <section className="space-y-1.5">
            <h2 className="text-sm font-semibold text-foreground">5. Intellectual Property</h2>
            <p>
              Arigato Labs, the Arigato Labs logo, Time Matrix, and related brand assets are proprietary intellectual property of Arigato Labs and founder Kumar Devanshu.
            </p>
          </section>

          <section className="space-y-1.5">
            <h2 className="text-sm font-semibold text-foreground">6. Automated Predictions & Recommendations</h2>
            <p>
              Recommendations generated by Time Matrix are mathematical heuristics, descriptive statistics, and multi-armed bandit calculations based on historical data. They do not constitute a guarantee of views, reach, or engagement, as external social media algorithms are controlled solely by third-party platforms.
            </p>
          </section>

          <section className="space-y-1.5">
            <h2 className="text-sm font-semibold text-foreground">7. Availability</h2>
            <p>
              The service is provided on an "as is" and "as available" basis without uptime or uninterrupted operation guarantees.
            </p>
          </section>

          <section className="space-y-1.5">
            <h2 className="text-sm font-semibold text-foreground">8. Termination</h2>
            <p>
              We reserve the right to suspend or terminate access in cases of service abuse or security violations.
            </p>
          </section>

          <section className="space-y-1.5">
            <h2 className="text-sm font-semibold text-foreground">9. Governing Law</h2>
            <p>
              Disputes arising under these Terms shall be governed by the laws of India under the founder's jurisdiction.
            </p>
          </section>

          <section className="space-y-1.5">
            <h2 className="text-sm font-semibold text-foreground">10. Contact</h2>
            <p>
              Questions regarding these Terms can be addressed to <a href="mailto:kumardevanshu3001@gmail.com" className="text-foreground hover:underline font-mono">kumardevanshu3001@gmail.com</a>.
            </p>
          </section>

        </div>

      </main>

      <LegalFooter onNavigate={onNavigate} />

    </div>
  );
};
